#define ENFORCE_TPSDIFF 1
#define ENFORCE_BRAKETHROTTLEDIFF 2

#define IN_TPS1 A0
#define IN_TPS2 A1
#define IN_APPS1 A2
#define IN_APPS2 A3
#define IN_BSE1 A4
#define IN_BSE2 A5
#define IN_PADDLEUP D0
#define IN_PADDLEDOWN D1
#define IN_WHEELSPEED D18
#define IN_RPM D6

#define OUT_SHIFTUP D2
#define OUT_SHIFTDOWN D3
#define OUT_CLUTCH D4
#define OUT_BRAKELIGHT D5
#define OUT_THROTTLE A6

#define NO_THROTTLE 0
#define FULL_THROTTLE 1

#define TIMER_WIRING 0
#define TIMER_APPSDIFF 1
#define TIMER_TPSDIFF 2
#define TIMER_SIGNALRANGE 3
#define TIMER_BRAKETHROTTLEDIFF 4
#define TIMER_EXPTPSDIFF 5
