#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ENFORCE_EXPTPSDIFF 1
#define ENFORCE_BRAKETHROTTLEDIFF 2

#define IN_TPS1 A0
#define IN_TPS2 A1
#define IN_APPS1 A2
#define IN_APPS2 A3
#define IN_BSE1 A4
#define IN_BSE2 A5
#define IN_PADDLEUP 0
#define IN_PADDLEDOWN 1
#define IN_WHEELSPEED 18
#define IN_RPM 6

#define OUT_SHIFTUP 2
#define OUT_SHIFTDOWN 3
#define OUT_CLUTCH 4
#define OUT_BRAKELIGHT 5
#define OUT_THROTTLE A6

#define NO_THROTTLE 0
#define FULL_THROTTLE 1

#define TIMER_WIRING 0
#define TIMER_APPSDIFF 1
#define TIMER_TPSDIFF 2
#define TIMER_SIGNALRANGE 3
#define TIMER_BRAKETHROTTLEDIFF 4
#define TIMER_EXPTPSDIFF 5

#define PULSE_SHIFTUP_PERIOD 1000
#define PULSE_SHIFTUP_AMPLITUDE 1
#define PULSE_SHIFTDOWN_PERIOD 1000
#define PULSE_SHIFTDOWN_AMPLITUDE 1
#define PULSE_CLUTCHOUT_TIME 100
#define PULSE_CLUTCHIN_TIME 100

#endif
